# ***************************
#   User parameters
# ***************************
# Number of polytopes
k: 5 #2, 3, 4, 5, 10 
# Dimension of the subspace in which each polytope lies
n: 5000 # 100, 500, 1000, 2000
# list of `k` integers, each indicating the n. of points to be used to generate intersecting polytopes
# if `0` is given, n_points is generated randomly
n_points: 0
#n_points: [12, 8]
#n_points: [12, 8, 25]
#n_points: [12, 8, 25, 50, 30]
#n_points: [12, 8, 25, 50, 30, 23, 60, 37, 25, 10]
# epsilon-optimality threshold
target_tolerance: 1e-06
# Number of FW iterations
max_iterations: 10000
# Number of FW iterations to compute optimal solution
max_iterations_opt: 50000
# How often FW iteration log is printed to screen
max_print_iterations: 10
# Set the seed for reproducibility
seed: 1
# Use FrankWolfe.ConvexHullOracle LMOs (true) or FrankWolfe.MathOptLMO LMOs (false)
cvxhflag: true