# ***************************
#   User parameters
# ***************************
# Number of polytopes
k: 2
# Dimension of the subspace in which each polytope lies
n: 4
# list of `k` integers, each indicating the n. of points to be used to generate intersecting polytopes 
n_points: 0
#n_points: [12, 8]
#n_points: [12, 8, 25]
#n_points: [12, 8, 25, 50, 30]
#n_points: [12, 8, 25, 50, 30, 23, 60, 37, 25, 10]
# epsilon-optimality threshold
target_tolerance: 1e-12
# Number of FW iterations
max_iterations: 1000000
# Set the seed for reproducibility
seed: 4