# ***************************
#   User parameters
# ***************************
# Number of polytopes
k: 2 #2, 3, 4, 5, 10 
# Dimension of the subspace in which each polytope lies
n: 5000 # 100, 500, 1000, 2000
# list of `k` integers, each indicating the n. of points to be used to generate `k` polytopes
# if `0` is given, n_points is generated randomly
n_points: 0
# epsilon-optimality threshold
target_tolerance: 1e-07
# epsilon-optimality threshold for finding optimal solution
target_tolerance_opt: 1e-08
# Number of FW iterations
max_iterations: 1000
# Number of FW iterations to compute optimal solution
max_iterations_opt: 10000
# How often FW iteration log is printed to screen
max_print_iterations: 100
# Set the seed for reproducibility
seed: 240389
# Use FrankWolfe.ConvexHullOracle LMOs (true) or FrankWolfe.MathOptLMO LMOs (false)
cvxhflag: true
# Intersect polytopes close to the first polytope's analytic center (true) or a vertex (false)
# Works well (true) if you only have two polytopes
anc_flag: true
# stepsize strategy: `0` is line search; `1` uses short-step with L=2 (specified in `product_algorithms.jl`)
stepsize_strategy: 0
