# ***************************
#   User parameters
# ***************************
# Number of polytopes
k: 2 #2, 3, 4, 5, 10 
# Dimension of the subspace in which each polytope lies
n: 500 # 100, 500, 1000, 2000
# list of `k` integers, each indicating the n. of points to be used to generate `k` polytopes
# if `0` is given, n_points is generated randomly
n_points: 0
# epsilon-optimality threshold
target_tolerance: 1e-07
# epsilon-optimality threshold for finding optimal solution
target_tolerance_opt: 1e-08
# Number of FW iterations
max_iterations: 1000
# Number of FW iterations to compute optimal solution
max_iterations_opt: 10000
# How often FW iteration log is printed to screen
max_print_iterations: 100
# Set the seed for reproducibility
seed: 240389
# Use FrankWolfe.ConvexHullOracle LMOs (true) or FrankWolfe.MathOptLMO LMOs (false)
cvxhflag: true
# Intersection parameters:
#
# - `intersection.anchor`: specify point in R^n where polytopes are aligned.
#   Allowed values:
#   - "p1_center"  : analytic center of the first polytope P₁
#   - "p1_vertex"  : a vertex of P₁
#   - "p1_random"  : random convex combination of vertices of P₁ (seeded by `seed`)
#   - "origin"     : the zero vector in R
#   - "global_mean": mean of all generated vertices across polytopes
#   - "random"     : random point in Rⁿ (seeded by `seed`)
#
# - `intersection.reference_point` specify which point of each polytope is moved onto the anchor.
#       Allowed values:
#         "center" : analytic center of each polytope
#         "vertex" : vertex of each polytope closest to the chosen anchor
intersection:
  anchor: "p1_center"
  reference_point: "vertex"
# stepsize strategy: `0` is line search; `1` uses short-step with L=2 (specified in `product_algorithms.jl`)
stepsize_strategy: 0
